/*
 * config.go - Renderer and system configuration management
 *
 * Reads and writes the renderer configuration file at
 * /data/etc/pi-clock-renderer.conf. This file is generated by the
 * pi-clock-config boot processor and read by the renderer at startup.
 *
 * The dashboard provides a web UI to edit these settings. Changes
 * are written back to the config file and the renderer picks them
 * up on its next update cycle.
 *
 * Copyright (C) 2026 Andy Taylor (MW0MWZ)
 * SPDX-License-Identifier: GPL-2.0-only
 */

package config

import (
	"bufio"
	"fmt"
	"os"
	"strings"
	"sync"
)

const (
	rendererConfPath = "/data/etc/pi-clock-renderer.conf"
)

// RendererConfig holds the display and station settings.
// Always used as a pointer. The mutex protects all fields from
// concurrent reads (template rendering) and writes (API handlers).
type RendererConfig struct {
	mu sync.RWMutex // guards all fields below

	CenterLon         string `json:"center_lon"`
	QthLat            string `json:"qth_lat"`
	QthLon            string `json:"qth_lon"`
	Callsign          string `json:"callsign"`
	GridSquare        string `json:"grid_square"`
	DisplayResolution string `json:"display_resolution"`
}

// Load reads the renderer config file and returns a RendererConfig.
func Load() *RendererConfig {
	cfg := &RendererConfig{
		CenterLon:         "0",
		QthLat:            "0",
		QthLon:            "0",
		Callsign:          "",
		GridSquare:        "",
		DisplayResolution: "native",
	}

	cfg.Reload()
	return cfg
}

// Reload re-reads the config file from disk.
func (c *RendererConfig) Reload() {
	c.mu.Lock()
	defer c.mu.Unlock()

	f, err := os.Open(rendererConfPath)
	if err != nil {
		return // File may not exist on first boot
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}

		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])

		switch key {
		case "CENTER_LON":
			c.CenterLon = val
		case "QTH_LAT":
			c.QthLat = val
		case "QTH_LON":
			c.QthLon = val
		case "CALLSIGN":
			c.Callsign = val
		case "GRID_SQUARE":
			c.GridSquare = val
		case "DISPLAY_RESOLUTION":
			c.DisplayResolution = val
		}
	}
}

// saveUnlocked writes the managed config fields back to disk, preserving
// any keys this struct doesn't own (e.g. DX_DISTANCE, DX_BANDS written
// directly by the DX settings API handler). Without this pass-through,
// saving QTH settings would silently erase DX filter settings.
//
// Caller MUST hold c.mu (write lock) before calling.
func (c *RendererConfig) saveUnlocked() error {
	managed := map[string]bool{
		"CENTER_LON": true, "QTH_LAT": true, "QTH_LON": true,
		"CALLSIGN": true, "GRID_SQUARE": true, "DISPLAY_RESOLUTION": true,
	}

	var extra []string
	if data, err := os.ReadFile(rendererConfPath); err == nil {
		for _, line := range strings.Split(string(data), "\n") {
			trimmed := strings.TrimSpace(line)
			if trimmed == "" || strings.HasPrefix(trimmed, "#") {
				continue
			}
			parts := strings.SplitN(trimmed, "=", 2)
			if len(parts) == 2 && !managed[parts[0]] {
				extra = append(extra, trimmed)
			}
		}
	}

	content := fmt.Sprintf(`# Pi-Clock renderer configuration
# Managed by the Pi-Clock dashboard
CENTER_LON=%s
QTH_LAT=%s
QTH_LON=%s
CALLSIGN=%s
GRID_SQUARE=%s
DISPLAY_RESOLUTION=%s
`, c.CenterLon, c.QthLat, c.QthLon, c.Callsign, c.GridSquare, c.DisplayResolution)

	for _, line := range extra {
		content += line + "\n"
	}

	/* Atomic write: write to temp file then rename. Prevents corrupt
	 * config if power is lost mid-write (common on Pi appliances). */
	tmp := rendererConfPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0644); err != nil {
		return err
	}
	return os.Rename(tmp, rendererConfPath)
}

// Save writes the current config back to disk (thread-safe).
func (c *RendererConfig) Save() error {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.saveUnlocked()
}

// Lock acquires the write lock. Used by handlers that modify the
// renderer config file directly (e.g. DX settings) to prevent
// concurrent writes from corrupting the file.
func (c *RendererConfig) Lock()   { c.mu.Lock() }
func (c *RendererConfig) Unlock() { c.mu.Unlock() }

// Snapshot returns a copy of the config fields under the read lock.
// Safe to pass to template rendering or JSON serialisation without
// holding the lock — the copy is independent of the original.
func (c *RendererConfig) Snapshot() RendererConfig {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return RendererConfig{
		CenterLon:         c.CenterLon,
		QthLat:            c.QthLat,
		QthLon:            c.QthLon,
		Callsign:          c.Callsign,
		GridSquare:        c.GridSquare,
		DisplayResolution: c.DisplayResolution,
	}
}

// Update applies new values from a map and saves atomically.
// Holds the write lock through both the field update and the
// file write to prevent TOCTOU races.
func (c *RendererConfig) Update(values map[string]string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	// Reject values containing newlines — they would inject extra
	// KEY=VALUE lines into the config file.
	for _, v := range values {
		if strings.ContainsAny(v, "\n\r") {
			return fmt.Errorf("invalid characters in config value")
		}
	}

	if v, ok := values["center_lon"]; ok {
		c.CenterLon = v
	}
	if v, ok := values["qth_lat"]; ok {
		c.QthLat = v
	}
	if v, ok := values["qth_lon"]; ok {
		c.QthLon = v
	}
	if v, ok := values["callsign"]; ok {
		c.Callsign = v
	}
	if v, ok := values["grid_square"]; ok {
		c.GridSquare = v
	}
	if v, ok := values["display_resolution"]; ok {
		c.DisplayResolution = v
	}

	return c.saveUnlocked()
}
