/*
 * borders.c - Country border data loading
 *
 * Reads the compact binary border data file generated by
 * generate_borders.py from Natural Earth shapefiles.
 *
 * The binary format is deliberately simple: a count followed by
 * arrays of floats. No endianness conversion is needed because
 * both the build system (Docker on ARM/x86) and the target (Pi)
 * are little-endian. If big-endian support is ever needed, add
 * byte-swap helpers here.
 *
 * Copyright (C) 2026 Andy Taylor (MW0MWZ)
 * SPDX-License-Identifier: GPL-2.0-only
 */

#include "borders.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

/*
 * pic_borders_load - Load border polygons from a binary file.
 *
 * File layout:
 *   [4 bytes] num_polygons (uint32_t)
 *   For each polygon:
 *     [4 bytes] num_points (uint32_t)
 *     [num_points * 4 bytes] longitudes (float[])
 *     [num_points * 4 bytes] latitudes (float[])
 */
int pic_borders_load(const char *path, pic_borders_t *borders)
{
    FILE *f;
    uint32_t i;

    memset(borders, 0, sizeof(*borders));

    f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "borders: cannot open '%s'\n", path);
        return -1;
    }

    /* Read polygon count */
    if (fread(&borders->num_polygons, sizeof(uint32_t), 1, f) != 1) {
        fprintf(stderr, "borders: failed to read header from '%s'\n", path);
        fclose(f);
        return -1;
    }

    /* Sanity-check polygon count against obviously corrupt data.
     * Natural Earth borders have ~4000 polygons; timezone/CQ zone
     * overlays have a few hundred. 100k is a generous upper bound. */
    if (borders->num_polygons > 100000) {
        fprintf(stderr, "borders: suspicious polygon count %u in '%s'\n",
                borders->num_polygons, path);
        fclose(f);
        return -1;
    }

    printf("borders: loading %u polygons from '%s'\n",
           borders->num_polygons, path);

    /* Allocate polygon array */
    borders->polygons = calloc(borders->num_polygons, sizeof(pic_polygon_t));
    if (!borders->polygons) {
        fprintf(stderr, "borders: allocation failed for %u polygons\n",
                borders->num_polygons);
        fclose(f);
        return -1;
    }

    /* Read each polygon's point data */
    for (i = 0; i < borders->num_polygons; i++) {
        pic_polygon_t *poly = &borders->polygons[i];

        /* Read point count */
        if (fread(&poly->num_points, sizeof(uint32_t), 1, f) != 1) {
            fprintf(stderr, "borders: failed reading polygon %u header\n", i);
            goto fail;
        }

        /* Validate point count and guard against size_t overflow on
         * 32-bit ARM where num_points * sizeof(float) can wrap. */
        if (poly->num_points > 500000 ||
            (size_t)poly->num_points > SIZE_MAX / sizeof(float)) {
            fprintf(stderr, "borders: polygon %u has suspicious "
                    "point count %u\n", i, poly->num_points);
            goto fail;
        }

        /* Allocate coordinate arrays */
        poly->lons = malloc(poly->num_points * sizeof(float));
        poly->lats = malloc(poly->num_points * sizeof(float));
        if (!poly->lons || !poly->lats) {
            fprintf(stderr, "borders: allocation failed for polygon %u "
                    "(%u points)\n", i, poly->num_points);
            goto fail;
        }

        /* Read longitude and latitude arrays */
        if (fread(poly->lons, sizeof(float), poly->num_points, f)
            != poly->num_points) {
            fprintf(stderr, "borders: failed reading polygon %u lons\n", i);
            goto fail;
        }
        if (fread(poly->lats, sizeof(float), poly->num_points, f)
            != poly->num_points) {
            fprintf(stderr, "borders: failed reading polygon %u lats\n", i);
            goto fail;
        }
    }

    fclose(f);
    printf("borders: loaded successfully\n");
    return 0;

fail:
    fclose(f);
    pic_borders_free(borders);
    return -1;
}

/*
 * pic_borders_free - Release all memory for border data.
 */
void pic_borders_free(pic_borders_t *borders)
{
    uint32_t i;

    if (borders->polygons) {
        for (i = 0; i < borders->num_polygons; i++) {
            free(borders->polygons[i].lons);
            free(borders->polygons[i].lats);
        }
        free(borders->polygons);
    }

    memset(borders, 0, sizeof(*borders));
}
