/*
 * layers_ituzone.c - ITU Zone overlay layer
 *
 * Draws the 90 ITU Zone boundaries and zone number labels.
 * Boundaries are loaded from a binary data file generated by
 * generate_ituzones.py from HB9HIL's GeoJSON dataset.
 *
 * Drawn in cyan/teal to distinguish from the orange CQ zones.
 *
 * Copyright (C) 2026 Andy Taylor (MW0MWZ)
 * SPDX-License-Identifier: GPL-2.0-only
 */

#include "layer.h"
#include "config.h"
#include "borders.h"
#include <cairo/cairo.h>
#include <math.h>
#include <stdio.h>

void pic_layer_render_ituzone(cairo_t *cr, int width, int height,
                              time_t now, void *user_data)
{
    pic_borders_t *itu_data = (pic_borders_t *)user_data;
    uint32_t i;
    double half_width;
    double dashes[] = {4.0, 4.0};
    double font_size;

    (void)now;

    if (!itu_data || itu_data->num_polygons == 0) {
        return;
    }

    half_width = width / 2.0;
    font_size = height / 90.0;

    /* Draw ITU Zone boundaries as dashed cyan lines.
     * Slightly thinner than CQ zones and with a different dash
     * pattern so both can be enabled simultaneously. */
    cairo_set_dash(cr, dashes, 2, 0);
    cairo_set_source_rgba(cr, 0.2, 0.8, 0.9, 0.40);
    cairo_set_line_width(cr, 1.0);
    cairo_set_line_join(cr, CAIRO_LINE_JOIN_ROUND);

    for (i = 0; i < itu_data->num_polygons; i++) {
        pic_polygon_t *poly = &itu_data->polygons[i];
        uint32_t j;
        double prev_x;

        if (poly->num_points < 2) {
            continue;
        }

        prev_x = pic_lon_to_x((double)poly->lons[0], width);
        cairo_move_to(cr,
                      prev_x,
                      pic_lat_to_y((double)poly->lats[0], height));

        for (j = 1; j < poly->num_points; j++) {
            double x = pic_lon_to_x((double)poly->lons[j], width);
            double y = pic_lat_to_y((double)poly->lats[j], height);

            /* Break the line at the antimeridian to prevent
             * horizontal stripes across the entire map. */
            if (fabs(x - prev_x) > half_width) {
                cairo_move_to(cr, x, y);
            } else {
                cairo_line_to(cr, x, y);
            }

            prev_x = x;
        }
    }

    cairo_stroke(cr);
    cairo_set_dash(cr, NULL, 0, 0);

    /*
     * Draw zone number labels at the bounding box centre of each
     * polygon. ITU zones are 1-90. Labels use a smaller font than
     * CQ zones since there are more of them and they'd overlap.
     *
     * The label is polygon index + 1, which assumes exactly one
     * polygon per zone (no MultiPolygons in the HB9HIL dataset).
     * The generator sorts by zone number so index order matches.
     */
    cairo_select_font_face(cr, "sans-serif",
                           CAIRO_FONT_SLANT_NORMAL,
                           CAIRO_FONT_WEIGHT_BOLD);
    cairo_set_font_size(cr, font_size);

    for (i = 0; i < itu_data->num_polygons; i++) {
        pic_polygon_t *poly = &itu_data->polygons[i];
        uint32_t j;
        double min_lon, max_lon, min_lat, max_lat;
        double cx, cy;
        char label[8];
        cairo_text_extents_t extents;
        int zone_num = (int)i + 1;

        if (poly->num_points < 3) {
            continue;
        }

        /* Bounding box centre — more visually stable than
         * vertex centroid for irregularly shaped zones. */
        min_lon = max_lon = poly->lons[0];
        min_lat = max_lat = poly->lats[0];
        for (j = 1; j < poly->num_points; j++) {
            if (poly->lons[j] < min_lon) min_lon = poly->lons[j];
            if (poly->lons[j] > max_lon) max_lon = poly->lons[j];
            if (poly->lats[j] < min_lat) min_lat = poly->lats[j];
            if (poly->lats[j] > max_lat) max_lat = poly->lats[j];
        }

        cx = pic_lon_to_x((min_lon + max_lon) / 2.0, width);
        cy = pic_lat_to_y((min_lat + max_lat) / 2.0, height);

        /* Skip if off-screen */
        if (cx < 0 || cx > width || cy < 0 || cy > height) {
            continue;
        }

        snprintf(label, sizeof(label), "%d", zone_num);
        cairo_text_extents(cr, label, &extents);

        /* Subtle background for readability */
        cairo_set_source_rgba(cr, 0.0, 0.0, 0.0, 0.3);
        cairo_rectangle(cr,
                        cx - extents.width / 2 - 2,
                        cy - extents.height / 2 - 2,
                        extents.width + 4,
                        extents.height + 4);
        cairo_fill(cr);

        /* Zone number in cyan */
        cairo_set_source_rgba(cr, 0.3, 0.85, 0.95, 0.8);
        cairo_move_to(cr,
                      cx - extents.width / 2,
                      cy + extents.height / 2);
        cairo_show_text(cr, label);
    }
}
